AUDIO_PROCESSING_INCLUDES	:= \
							   . \
							   ../webrtc/modules/audio_processing/ \
							   ../webrtc/modules/audio_processing/aec \
							   ../webrtc/modules/audio_processing/aecm \
							   ../webrtc/modules/audio_processing/agc \
							   ../webrtc/modules/audio_processing/agc/legacy \
							   ../webrtc/modules/audio_processing/beamformer \
							   ../webrtc/modules/audio_processing/echo_detector \
							   ../webrtc/modules/audio_processing/include \
							   ../webrtc/modules/audio_processing/intelligibility \
							   ../webrtc/modules/audio_processing/level_controller \
							   ../webrtc/modules/audio_processing/logging \
							   ../webrtc/modules/audio_processing/ns \
							   ../webrtc/modules/audio_processing/transient \
							   ../webrtc/modules/audio_processing/utility \
							   ../webrtc/modules/audio_processing/vad \

AUDIO_PROCESSING_SOURCE_PATH	:= ../webrtc/modules/audio_processing
AUDIO_PROCESSING_SOURCE_FILES	:= \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/aec_core.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/aec_core_neon.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/aec_resampler.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/echo_cancellation.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aecm/aecm_core.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aecm/aecm_core_c.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aecm/aecm_core_neon.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/aecm/echo_control_mobile.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/agc.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/agc_manager_direct.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/loudness_histogram.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/utility.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/legacy/digital_agc.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/legacy/analog_agc.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_buffer.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_processing_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/array_util.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/covariance_matrix_generator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/nonlinear_beamformer.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_cancellation_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_control_mobile_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/circular_buffer.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/mean_variance_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/normalized_covariance_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/gain_control_for_experimental_agc.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/gain_control_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/high_pass_filter_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/include/audio_processing.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/include/config.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/intelligibility/intelligibility_enhancer.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/intelligibility/intelligibility_utils.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/biquad_filter.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/down_sampler.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/gain_applier.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/gain_selector.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/level_controller.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/noise_level_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/noise_spectrum_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/peak_level_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/saturating_gain_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/signal_classifier.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/level_estimator_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/logging/apm_data_dumper.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/noise_suppression.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/noise_suppression_x.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/ns_core.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/nsx_core.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/nsx_core_c.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/nsx_core_neon.c \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/noise_suppression_impl.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/residual_echo_detector.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/rms_level.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/splitting_filter.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/three_band_filter_bank.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/click_annotate.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/file_utils.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/moving_moments.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/transient_detector.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/transient_suppressor.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/wpd_node.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/wpd_tree.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/typing_detection.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/block_mean_calculator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/delay_estimator.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/delay_estimator_wrapper.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/ooura_fft.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/ooura_fft_neon.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/gmm.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pitch_based_vad.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pitch_internal.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pole_zero_filter.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/standalone_vad.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/vad_audio_proc.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/vad_circular_buffer.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/voice_activity_detector.cc \
							   $(AUDIO_PROCESSING_SOURCE_PATH)/voice_detection_impl.cc \

OTHER_PLATFORM_FILES	:= \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/ns/nsx_core_mips.c \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/aec_core_mips.cc \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/aecm/aecm_core_mips.cc \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/ooura_fft_mips.cc \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/aec_core_sse2.cc \
						   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/ooura_fft_sse2.cc \

TEST_FILES	:= \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/echo_cancellation_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/aec/system_delay_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/agc_manager_direct_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/agc/loudness_histogram_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_buffer_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_processing_impl_locking_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_processing_impl_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_processing_performance_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/audio_processing_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/array_util_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/complex_matrix_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/covariance_matrix_generator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/matrix_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/nonlinear_beamformer_test.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/beamformer/nonlinear_beamformer_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/config_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_cancellation_bit_exact_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_cancellation_impl_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_control_mobile_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/circular_buffer_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/mean_variance_estimator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/echo_detector/normalized_covariance_estimator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/gain_control_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/high_pass_filter_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/intelligibility/intelligibility_enhancer_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/intelligibility/intelligibility_utils_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/intelligibility/test/intelligibility_proc.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/level_controller_complexity_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/level_controller/level_controller_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/level_estimator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/noise_suppression_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/residual_echo_detector_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/splitting_filter_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/aec_dump_based_simulator.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/audio_buffer_tools.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/audio_processing_simulator.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/audioproc_float.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/bitexactness_tools.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/debug_dump_replayer.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/debug_dump_test.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/protobuf_utils.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/test_utils.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/unpack.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/test/wav_based_simulator.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/dyadic_decimator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/file_utils_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/moving_moments_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/transient_detector_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/transient_suppression_test.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/transient_suppressor_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/wpd_node_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/transient/wpd_tree_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/block_mean_calculator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/utility/delay_estimator_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/gmm_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pitch_based_vad_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pitch_internal_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/pole_zero_filter_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/standalone_vad_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/vad_audio_proc_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/vad_circular_buffer_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/vad/voice_activity_detector_unittest.cc \
			   $(AUDIO_PROCESSING_SOURCE_PATH)/voice_detection_unittest.cc \
